blank_issues_enabled: false
contact_links:
  - name: 📚 Documentacao
    url: https://github.com/ricardo-camilo-programador-frontend-web/alla-kayan-portfolio2.0/blob/main/docs/github-workflow/README.md
    about: Consulte a documentacao do projeto
